name: Upload to S3

on:
  push:
    branches:
      - main  # Trigger the action on push to the `main` branch

jobs:
  upload_to_s3:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up AWS CLI credentials using GitHub secrets
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-west-2'  # Specify your AWS region

      # Step 3: Install AWS CLI using the official AWS method
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      # Step 4: Upload files to S3
      - name: Upload files to S3
        run: |
          aws s3 sync . s3://your-bucket-name/ --exclude ".git/*" --content-type "text/html"
