name: Upload to S3

on:
  push:
    branches:
      - main

jobs:
  upload_to_s3:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-west-2'

      - name: Upload files to S3
        run: |
          aws s3 sync . s3://aspirecte.com/ --exclude ".git/*"
